version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: t3_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: touzen666
      POSTGRES_PASSWORD: MisioPysio2@
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
